server:
  port: 9000
spring:
  application:
    name: modular-monolith-example
  datasource:
    url: jdbc:postgresql://localhost:5432/modular-monolith-example
    username: postgres
    password: admin
  liquibase:
    change-log: classpath:db.changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: "health,modulith"
  tracing:
    sampling:
      probability: 1