server:
  port: 9000
spring:
  application:
    name: modular-monolith-example
  datasource:
    orders:
      url: jdbc:postgresql://localhost:5432/modular-monolith-example?currentSchema=orders
      username: postgres
      password: admin
      liquibase:
        change-log: classpath:orders/liquibase/changelog.xml
    products:
      url: jdbc:postgresql://localhost:5432/modular-monolith-example?currentSchema=products
      username: postgres
      password: admin
      liquibase:
        change-log: classpath:products/liquibase/changelog.xml

management:
  endpoints:
    web:
      exposure:
        include: "health,modulith"
  tracing:
    sampling:
      probability: 1